name: macOS checks

on: [push]

jobs:
  alire-macos-13:
    # This job runs with macOS 13 and the latest stable Xcode (v15),
    # which introduced the problem with ld-new (the default
    # implementation of ld) and ld-classic). The main effect seen with
    # this is sometimes-failing exception handling.
    runs-on: macos-13
    steps:
    -
      name: Check original ld version
      run: ld -v
    -
      name: Set Xcode version
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
    -
      name: Check updated ld version
      run: ld -v
    -
      name: Checkout
      uses: actions/checkout@v3
    -
      name: Set up Alire
      uses: alire-project/setup-alire@v2
      with:
        version: "nightly"
    -
      name: Install toolchain
      run: |
        alr --non-interactive config --global --set toolchain.assistant false
        alr --non-interactive toolchain --install gnat_native
        alr --non-interactive toolchain --install gprbuild
        alr --non-interactive toolchain --select gnat_native
        alr --non-interactive toolchain --select gprbuild
    -
      name: Build & run
      run: |
        cd xcode_issue
        alr --non-interactive build
        alr run --skip-build c380003
        alr run --skip-build c390002
        alr run --skip-build c43206a
